import React, { useState, useEffect } from 'react';
import { ChevronUp, ChevronDown } from 'lucide-react';
import { Textarea } from '@/components/ui/textarea';
import {
  BLOCK_DEFS,
  DEFAULT_VISUAL_CONFIG,
  configToScript,
  configToPreview,
  parseConfig,
} from '@/lib/statuslineConfig';

export default function StatuslineVisualEditor({ value, onChange }) {
  const [mode, setMode] = useState('visual');
  const [config, setConfig] = useState(() => parseConfig(value) || DEFAULT_VISUAL_CONFIG);

  // Sync config if parent loads a new script with a CONFIG comment
  useEffect(() => {
    const parsed = parseConfig(value);
    if (parsed) setConfig(parsed);
  }, [value]);

  const updateConfig = newConfig => {
    setConfig(newConfig);
    onChange(configToScript(newConfig));
  };

  const switchMode = newMode => {
    if (newMode === 'raw') {
      // Generate fresh script from current visual config
      onChange(configToScript(config));
    } else {
      // Sync visual from script if it has a CONFIG comment
      const parsed = parseConfig(value);
      if (parsed) setConfig(parsed);
    }
    setMode(newMode);
  };

  const moveBlock = (i, dir) => {
    const blocks = [...config.blocks];
    const j = i + dir;
    if (j < 0 || j >= blocks.length) return;
    [blocks[i], blocks[j]] = [blocks[j], blocks[i]];
    updateConfig({ ...config, blocks });
  };

  const hasConfigComment = !!parseConfig(value);

  return (
    <div className="space-y-2">
      {/* Mode tabs */}
      <div className="flex gap-1 bg-gray-100 dark:bg-slate-800 rounded-lg p-1 w-fit">
        {[['visual', 'Visual'], ['raw', 'Raw Bash']].map(([m, label]) => (
          <button
            key={m}
            onClick={() => switchMode(m)}
            className={`px-3 py-1 rounded text-xs font-medium transition-colors ${
              mode === m
                ? 'bg-white dark:bg-slate-700 text-gray-900 dark:text-white shadow-sm'
                : 'text-gray-500 dark:text-slate-400 hover:text-gray-700 dark:hover:text-slate-300'
            }`}
          >
            {label}
          </button>
        ))}
      </div>

      {mode === 'visual' ? (
        <div className="space-y-2">
          {/* Notice when script wasn't generated by visual editor */}
          {!hasConfigComment && value?.trim() && (
            <p className="text-xs text-amber-500 dark:text-amber-400">
              This script wasn't generated by the visual editor — showing template.{' '}
              <button
                onClick={() => updateConfig(DEFAULT_VISUAL_CONFIG)}
                className="underline hover:no-underline"
              >
                Reset to default
              </button>
            </p>
          )}

          {/* Preview bar */}
          <div className="px-2 py-1.5 bg-gray-950 rounded font-mono text-[11px] border border-gray-800 text-gray-300 truncate whitespace-pre">
            {configToPreview(config)}
          </div>

          {/* Prefix / Separator */}
          <div className="flex gap-2">
            {[['Prefix', 'prefix'], ['Separator', 'separator']].map(([label, key]) => (
              <label key={key} className="flex-1">
                <span className="text-xs text-gray-500 dark:text-slate-400 block mb-0.5">{label}</span>
                <input
                  type="text"
                  value={config[key]}
                  onChange={e => updateConfig({ ...config, [key]: e.target.value })}
                  className="w-full text-xs px-2 py-1 rounded border border-gray-200 dark:border-slate-700 bg-white dark:bg-slate-900 text-gray-900 dark:text-white font-mono"
                />
              </label>
            ))}
          </div>

          {/* Block list */}
          <div className="space-y-0.5">
            {config.blocks.map((block, i) => {
              const def = BLOCK_DEFS.find(d => d.id === block.id);
              if (!def) return null;
              return (
                <div
                  key={block.id}
                  className="flex items-center gap-2 px-2 py-1.5 rounded bg-gray-50 dark:bg-slate-900 border border-gray-100 dark:border-slate-800"
                >
                  {/* Reorder */}
                  <div className="flex flex-col -my-0.5 shrink-0">
                    <button
                      onClick={() => moveBlock(i, -1)}
                      disabled={i === 0}
                      className="text-gray-300 dark:text-slate-700 hover:text-gray-600 dark:hover:text-slate-400 disabled:opacity-30 disabled:cursor-not-allowed leading-none"
                    >
                      <ChevronUp className="w-3 h-3" />
                    </button>
                    <button
                      onClick={() => moveBlock(i, 1)}
                      disabled={i === config.blocks.length - 1}
                      className="text-gray-300 dark:text-slate-700 hover:text-gray-600 dark:hover:text-slate-400 disabled:opacity-30 disabled:cursor-not-allowed leading-none"
                    >
                      <ChevronDown className="w-3 h-3" />
                    </button>
                  </div>

                  {/* Checkbox */}
                  <input
                    type="checkbox"
                    checked={block.enabled}
                    onChange={e =>
                      updateConfig({
                        ...config,
                        blocks: config.blocks.map(b =>
                          b.id === block.id ? { ...b, enabled: e.target.checked } : b
                        ),
                      })
                    }
                    className="rounded shrink-0 accent-indigo-500"
                  />

                  {/* Label */}
                  <span
                    className={`flex-1 text-xs font-medium ${
                      block.enabled
                        ? 'text-gray-900 dark:text-white'
                        : 'text-gray-400 dark:text-slate-600'
                    }`}
                  >
                    {def.label}
                  </span>

                  {/* Preview chip */}
                  <span className="text-[10px] text-gray-400 dark:text-slate-600 font-mono shrink-0 hidden sm:block">
                    {def.preview}
                  </span>

                  {/* Style selector for context-bar */}
                  {block.id === 'context-bar' && block.enabled && (
                    <select
                      value={block.style || 'dots'}
                      onChange={e =>
                        updateConfig({
                          ...config,
                          blocks: config.blocks.map(b =>
                            b.id === 'context-bar' ? { ...b, style: e.target.value } : b
                          ),
                        })
                      }
                      className="text-xs px-1.5 py-0.5 rounded border border-gray-200 dark:border-slate-700 bg-white dark:bg-slate-900 text-gray-900 dark:text-white shrink-0"
                    >
                      <option value="dots">●○ dots</option>
                      <option value="blocks">█░ blocks</option>
                    </select>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      ) : (
        <Textarea
          value={value}
          onChange={e => onChange(e.target.value)}
          className="font-mono text-xs h-48 resize-y bg-gray-950 dark:bg-black text-green-400 border-gray-800"
          spellCheck={false}
          autoFocus
        />
      )}
    </div>
  );
}
